### ISSUE TITLE
Can't (de)select spectra for long spectroscopic time-series

### ISSUE THREAD

**Issue by steveschulze** [fritz-marshal/fritz-beta-feedback#95]
Problem: If the legend exceeds a critical length, it's not possible anymore to select or deselect more recent spectra. A screenshot from ZTF21aakilyd is attached.

![Screenshot 2021-04-03 at 13 18 55](https://user-images.githubusercontent.com/11585543/113477042-a1b9d500-947f-11eb-9b6a-af8092d31460.png)

**Comment by scizen9** [comment]
[Issue#97](https://github.com/fritz-marshal/fritz-beta-feedback/issues/97) addresses this more generally to include photometry plots, which can have the same problem.

**Comment by kmshin1397** [comment]
Related issue has been addressed (long legends getting cut off)

**Comment by steveschulze** [comment]
Hi,

This problem still exists. See the screenshot below.

Cheers,

Steve

![Screenshot 2021-06-29 at 21 19 57](https://user-images.githubusercontent.com/11585543/123855174-dc68c780-d91f-11eb-90f4-cd63364707f3.png)

**Comment by kmshin1397** [comment]
Ah yes, sorry for closing this prematurely. A fix has been implemented as part of https://github.com/skyportal/skyportal/pull/2085, but I forgot that this hasn't been merged/deployed yet.

**Comment by guynir42** [comment]
I believe this is sorted out in https://github.com/skyportal/skyportal/pull/2085
